// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMI5ezgGSRZBU8IjklF9fXcBC_PAhqOhc',
    appId: '1:428205013850:web:a66485ae9a1e79ee289163',
    messagingSenderId: '428205013850',
    projectId: 'construction-rfq-itay-20-2eee0',
    authDomain: 'construction-rfq-itay-20-2eee0.firebaseapp.com',
    storageBucket: 'construction-rfq-itay-20-2eee0.firebasestorage.app',
    measurementId: 'G-K0MWT9XX2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtldj2OmXdUne8aJVxlfdKEAcn2mrpOmE',
    appId: '1:428205013850:android:65c1a58aca4f7226289163',
    messagingSenderId: '428205013850',
    projectId: 'construction-rfq-itay-20-2eee0',
    storageBucket: 'construction-rfq-itay-20-2eee0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcSnnejigcHzhFOMmak8tj2lk-egzLKlY',
    appId: '1:428205013850:ios:cc6f367c20f872cf289163',
    messagingSenderId: '428205013850',
    projectId: 'construction-rfq-itay-20-2eee0',
    storageBucket: 'construction-rfq-itay-20-2eee0.firebasestorage.app',
    iosClientId: '428205013850-24hfvb0ja7tgi3e5sjlhao0kacn5b04b.apps.googleusercontent.com',
    iosBundleId: 'com.construction.constructionRfq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcSnnejigcHzhFOMmak8tj2lk-egzLKlY',
    appId: '1:428205013850:ios:cc6f367c20f872cf289163',
    messagingSenderId: '428205013850',
    projectId: 'construction-rfq-itay-20-2eee0',
    storageBucket: 'construction-rfq-itay-20-2eee0.firebasestorage.app',
    iosClientId: '428205013850-24hfvb0ja7tgi3e5sjlhao0kacn5b04b.apps.googleusercontent.com',
    iosBundleId: 'com.construction.constructionRfq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMI5ezgGSRZBU8IjklF9fXcBC_PAhqOhc',
    appId: '1:428205013850:web:174a6f66bf43cdb2289163',
    messagingSenderId: '428205013850',
    projectId: 'construction-rfq-itay-20-2eee0',
    authDomain: 'construction-rfq-itay-20-2eee0.firebaseapp.com',
    storageBucket: 'construction-rfq-itay-20-2eee0.firebasestorage.app',
    measurementId: 'G-ZXJ2950W94',
  );

}