enum Permission {
  viewCatalog,
  createDraft,
  addItems,
  submitRfq,
  approveProcurementRfq,
  rejectProcurementRfq,
  approveQuote,
  rejectQuote,
  createSupplierQuote,
  markShipped,
  manageUsers,
  inviteMembers,
  manageProjects,
  viewReports,
  platformManageAll,
}
